### ISSUE TITLE
[BUG] Tip Interval zu schnell

### ISSUE THREAD

**Issue by Flash2over** [raidcraft/rctips#9]
![image](https://user-images.githubusercontent.com/2538458/104823085-bf47ad00-5847-11eb-8cad-f8a8fa0d37d9.png)

**Comment by Flash2over** [comment]
Das klicken auf OK funktioniert auch nicht.

**Comment by PhilipU** [comment]
Es war noch eine alte Version auf dem Server + Config nicht up-to-date
